export const API_ENDPOINTS = {
  BASE_URL: import.meta.env.VITE_API_BASE_URL,
  USER: import.meta.env.VITE_API_USER_URL,
  LEARNING_FORM: import.meta.env.VITE_API_LEARNING_FORM_URL,
  COURSE: import.meta.env.VITE_API_COURSE_URL,
  PROGRESS: import.meta.env.VITE_API_PROGRESS_URL,
};
API_ENDPOINTS.EMPLOYEES = `${API_ENDPOINTS.USER}/employees`;

export const LEARNING_FORM_ENDPOINTS = {
  TOP_LEARNERS_MONTH: `${API_ENDPOINTS.LEARNING_FORM}/top-month`,
  TOP_LEARNERS_WEEK: `${API_ENDPOINTS.LEARNING_FORM}/top-week`,
};
